import JSZip from 'jszip';
import { readTourData, listImageFiles, getFileFromOPFS, getTourHandle } from '@trikomi/core/tour';

/**
 * Exports a tour as a self-contained ZIP that can be hosted anywhere.
 *
 * ZIP structure:
 *   index.html          ← viewer entry point (token injected)
 *   assets/             ← JS, CSS, WASM (from /export-dist/assets/)
 *   tour.json           ← tour data
 *   images/             ← all panorama images and media
 *
 * Works in both dev (Vite serves public/export-dist/) and production
 * (public/export-dist/ is copied to dist/ automatically by Vite).
 */
export const exportApi = {
  exportTourAsZip: async (tourId, licenseToken, onProgress) => {
    onProgress?.('Reading tour data...', 5);

    const tourHandle = await getTourHandle(tourId);
    const tourData = await readTourData(tourHandle);
    if (!tourData) throw new Error('Tour data not found.');

    const zip = new JSZip();

    // ── 1. tour.json ──────────────────────────────────────────────────────────
    zip.file('tour.json', JSON.stringify(tourData, null, 2));

    // ── 2. Images from OPFS ───────────────────────────────────────────────────
    onProgress?.('Adding images...', 10);
    const imageFiles = await listImageFiles(tourId);
    let loadedImages = 0;

    for (const fileObj of imageFiles) {
      const fileName = fileObj.original_name || fileObj.id;
      const file = await getFileFromOPFS(tourId, fileName);
      if (file) {
        zip.file(`images/${fileName}`, file);
      }
      loadedImages++;
      onProgress?.(
        `Adding images... (${loadedImages}/${imageFiles.length})`,
        10 + (loadedImages / imageFiles.length) * 35
      );
    }

    // ── 3. Viewer assets ──────────────────────────────────────────────────────
    onProgress?.('Fetching viewer assets...', 45);

    // Fetch the asset list generated by `yarn build:export`
    let assetList;
    try {
      const res = await fetch('/export-dist/asset-list.json');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      assetList = await res.json(); // string[], e.g. ["index.html", "assets/index-xxx.js", ...]
    } catch (_err) {
      throw new Error(
        'Viewer template not found. Please run "yarn build:export" and reload.'
      );
    }

    // index.html: fetch and inject the license token
    const indexHtml = await fetch('/export-dist/index.html').then(r => r.text());
    
    let injectedToken = licenseToken ?? '';
    
    // If the license is a file path (e.g. .lic file), fetch and bundle it
    if (licenseToken && licenseToken.endsWith('.lic')) {
      try {
        const licName = licenseToken.split('/').pop();
        const licBlob = await fetch(licenseToken).then(r => r.blob());
        zip.file(`assets/${licName}`, licBlob);
        injectedToken = `./assets/${licName}`;
      } catch (err) {
        console.error('Failed to bundle license file:', err);
      }
    }

    const injectedHtml = indexHtml.replace('%%INJECT_TOKEN%%', injectedToken);
    zip.file('index.html', injectedHtml);

    // All other assets
    const otherAssets = assetList.filter(f => f !== 'index.html' && f !== 'asset-list.json');
    let loadedAssets = 0;

    for (const filePath of otherAssets) {
      const blob = await fetch(`/export-dist/${filePath}`).then(r => r.blob());
      zip.file(filePath, blob);
      loadedAssets++;
      onProgress?.(
        `Fetching viewer assets... (${loadedAssets}/${otherAssets.length})`,
        45 + (loadedAssets / otherAssets.length) * 45
      );
    }

    // ── 4. Generate ZIP and trigger download ──────────────────────────────────
    onProgress?.('Generating ZIP...', 92);

    const safeTitle = (tourData.title || 'tour')
      .replace(/[^a-z0-9]/gi, '-')
      .toLowerCase()
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    const content = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });

    const url = URL.createObjectURL(content);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${safeTitle}-tour.zip`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    setTimeout(() => URL.revokeObjectURL(url), 10000);

    onProgress?.('Download started!', 100);
  },
};
